structure_injector:
  enabled: false
  default_chance: 5.0
  notify_on_add: false
  rarity_apply_to_items: true
  vaults:
    enabled: false
    normal_chance: 7.5
    ominous_chance: 12.5
    normal_loot_mode: all
    ominous_loot_mode: all
    normal_mystery_state: all
    ominous_mystery_state: all
  structures:
    minecraft:trial_chambers: 12.5
    minecraft:ancient_city: 8.0
  loot_mode:
    minecraft:trial_chambers: item_only
  mystery_state:
    minecraft:trial_chambers: mystery_only
  book_rarity: {}

librarian_trades:
  enabled: false
  trades:
    - enchant: divine_vision
      level: 1
      chance: 25.0
      emeralds: 16
      books: 1

bundle_drop:
  enabled: false
  chance: 5.0 # default chance used when quickly enabling mobs in the bundle GUI
  mob_chance: {}
  rewards: []
  extra_drops: []
