name: ForbiddenEnchants
version: 1.0.3
main: dev.cevapi.forbiddenenchants.ForbiddenEnchantsPlugin
api-version: '1.21'
author: CevAPI

commands:
  fe:
    description: Forbidden Enchants admin tools.
    usage: /fe help

permissions:
  forbiddenenchants.admin:
    default: op

